
COMPONENT_SRCDIRS := .
COMPONENT_SRCDIRS += core/HttpClient
COMPONENT_SRCDIRS += core/HttpServer
COMPONENT_SRCDIRS += core/I2C
COMPONENT_SRCDIRS += core/Sd
COMPONENT_SRCDIRS += core/Spi
COMPONENT_SRCDIRS += core/Uart
COMPONENT_SRCDIRS += core/Wifi


COMPONENT_ADD_INCLUDEDIRS := .
COMPONENT_ADD_INCLUDEDIRS += core/HttpClient
COMPONENT_ADD_INCLUDEDIRS += core/HttpServer
COMPONENT_ADD_INCLUDEDIRS += core/I2C
COMPONENT_ADD_INCLUDEDIRS += core/Sd
COMPONENT_ADD_INCLUDEDIRS += core/Spi
COMPONENT_ADD_INCLUDEDIRS += core/Uart
COMPONENT_ADD_INCLUDEDIRS += core/Wifi


